web/themes/custom/agid/templates/form/input--submit.html.twig

Fix https://trello.com/c/fR0qQkuM

Added submit button template

---

web/themes/custom/agid/templates/layout/page--front.html.twig

Fix https://trello.com/c/0NRB6M5o

Added page--front template

---

web/themes/custom/agid/agid.theme
web/themes/custom/agid/css/agid.css
web/themes/custom/agid/templates/fields/field--node--field-repository-files--page.html.twig

Fix https://trello.com/c/LNyQlANp

Attached docs fix

---

composer.json
composer.lock
config/agid/sync/core.extension.yml
config/agid/sync/seckit.settings.yml
config/agid/sync/views.view.dove_pagare.yml

* Installare i nuovi moduli aggiunti con composer
* **composer install**
* Importa delle configurazioni del modulo seckit
* **bin/drupal config:import**

 AGID-155 aggiungere modulo securitykit (249)

---

config/agid/sync/views.view.dove_pagare.yml

* Dopo essersi accertati che le configurazioni attive siano allineate con quelle esportate in file, dopodichè effettuare: 
* **bin/drupal config-import**

AGID-149 Pago PA /Dove pagare: il bottone del form non è declinato graficamente come da proposta ed è in inglese (159)

---

.gitignore
web/themes/custom/agid/package-lock.json
web/themes/custom/agid/package.json

- moved dependencies to dev in package.json
- added npm scripts in package.json
- added node_modules to .gitignore

Updated SASS build pipeline

---

.gitignore
config/agid/sync/editor.editor.filtered_text.yml
config/agid/sync/filter.format.filtered_text.yml

* Effettuare l'import delle configurazioni
* **bin/drupal config:import**

AGID-160 Implementare la possibilità di inserire delle immagini con didascalia anche tra due blocchi di testo. (292)

---

.gitignore
web/themes/custom/agid/templates/content/node--view--home-page-highlight.html.twig

AGID-167 Linkare l'immagine del focus in home page al contenuto corrispondente (257)

---

.gitignore
web/modules/custom/agid_base/agid_base.module

AGID-164 limitare la possibilità di inserire titolazioni nell'editor wysiwyg (256)

---

.gitignore
composer.json
composer.lock
config/agid/sync/core.entity_form_display.node.page.default.yml
config/agid/sync/core.entity_view_display.node.page.default.yml
config/agid/sync/core.extension.yml
config/agid/sync/field.field.node.page.field_focus.yml
config/agid/sync/field.storage.node.field_focus.yml
config/agid/sync/views.view.focus_page.yml

* **bin/drupal config:import**
* Ailitare la voce "Focus" del menu "Main Navigation"

AGID-165 nuovo tag e sezione "focus" sotto 'stampa e comunicazione' (283)

---

config/agid/sync/sitemap.settings.yml
config/agid/sync/user.role.anonymous.yml
web/themes/custom/agid/css/sitemap.css
web/themes/custom/agid/js/sitemap.js

bin/drupal config:import
bin/drupal cache:rebuild all

AGID-185 Implementare mappa del sito e declinarla secondo mockup (154)

---

config/agid/sync/views.view._pagopa_enti_creditori_amministrazioni_aderenti.yml

* **bin/drupal config:import**

AGID-149 Pago PA /Dove pagare: il bottone del form non è declinato graficamente come da proposta ed è in inglese (159) - Rimuove testo vista.

---

web/themes/custom/agid/css/agid.css
web/themes/custom/agid/css/sitemap.css
web/themes/custom/agid/scss/module/_share.scss
web/themes/custom/agid/templates/share_everywhere/share-everywhere.html.twig

* **bin/drupal cache:rebuild all**

AGID-186 inserire un widget per condividere le notizie (155) - Fixa l'allineamento configurabile da modulo.

---

web/modules/custom/agid_twitter_block/src/Plugin/Block/TwitterBlock.php

* Effettuare pulizia delle cache

AGID-169 carousel twitter (295) - Fix twitter block. Esclude risposte.

---

web/modules/custom/agid_base/agid_base.module

* Eseguire pulizia delle cache

AGID-187 Problema multilingua ( translate contenuto singole voci di menu) (306)

---

web/themes/custom/agid/templates/block/block--views-block--home-page-notizie-tecniche-block-1.html.twig

* Effettuare pulizia delle cache

AGID-188 Definizione della gestione dei blocchi e delle sottocode in inglese (307) - Fix label del blocco Notizie tecniche.

---

config/agid/sync/block.block.homepageplatforms.yml
config/agid/sync/block.block.navigazioneprincipale_2.yml
config/agid/sync/block.block.navigazionesecondaria.yml
config/agid/sync/block.block.views_block__home_page_last_updates_block_1.yml
config/agid/sync/block.block.views_block__home_page_news_block_1.yml
config/agid/sync/block.block.views_block__home_page_notizie_tecniche_block_1.yml
config/agid/sync/views.view.home_page_news.yml
config/agid/sync/views.view.home_page_notizie_tecniche.yml
web/modules/custom/agid_twitter_block/templates/agid-twitter-block.html.twig
web/themes/custom/agid/css/agid.css
web/themes/custom/agid/scss/agid.scss
web/themes/custom/agid/scss/module/_twitter.scss
web/themes/custom/agid/scss/theme/_news.scss
web/themes/custom/agid/scss/theme/_views.scss
web/themes/custom/agid/templates/layout/page.html.twig
web/themes/custom/agid/templates/views/views-view-unformatted--home-page-news--block.html.twig

* Effettuare import delle configurazioni
* **bin/drupal ci**
* Effettuare cache rebuild

AGID-218 Modifiche alla home: blocco notizie (324) - Rifacimento Home Page

---

config/agid/sync/block.block.navigazioneprincipale_2.yml
config/agid/sync/block.block.navigazionesecondaria.yml
config/agid/sync/field.field.node.page.field_focus.yml
config/agid/sync/field.field.node.page.field_image.yml
config/agid/sync/field.field.node.page.field_link.yml
config/agid/sync/field.field.node.page.field_page_source.yml
config/agid/sync/language.content_settings.node.acc_subj.yml
config/agid/sync/language.content_settings.node.event.yml
config/agid/sync/language.content_settings.node.faq.yml
config/agid/sync/language.content_settings.node.news.yml
config/agid/sync/language.content_settings.node.pagopa.yml
config/agid/sync/language.content_settings.node.press.yml
config/agid/sync/language.content_settings.node.software.yml

* Effettuare importazione configurazioni
* **bin/drupal ci**
* Effettuare pulizia cache

AGID-218 Modifiche alla home: blocco notizie (324) - Nasconde i campi non traducibili dalla form di traduzione di un nodo.

---

web/themes/custom/agid/templates/fields/field--node--field-repository-files--page.html.twig

AGID-170 caricamento file: aggiungere campo data pubblicazione (297) - Fixa date che si replicano in ct pagina.

---

web/modules/custom/agid_base/agid_base.module

Rimane la funzionalità che nasconde le voci non tradotte in lingua.
* Effettua cr

AGID-187 Problema multilingua (306) - Ripristina funzionamento del menu nel modo standard.

---

web/sites/default/modules/custom/agid_migrate_tools/src/Plugin/migrate/source/FileEntity.php

Fixa agid_migration_tools, ora è necessario specificare source_module. Vedi: https://www.drupal.org/node/2831566

AGID-231 ripristinare tool di aggiornamento nodi sezione pagopa (346)

---

config/agid/sync/block.block.agid_languageswitcher.yml
config/agid/sync/block.block.slimheadermenu.yml
config/agid/sync/system.menu.slim-header-menu.yml
config/agid/sync/views.view.content.yml
web/themes/custom/agid/css/agid.css
web/themes/custom/agid/scss/agid.scss
web/themes/custom/agid/scss/module/_slim-menu.scss
web/themes/custom/agid/templates/block/block--header-top--slimheadermenu.html.twig
web/themes/custom/agid/templates/navigation/menu--slim-header-menu.html.twig

* Importare nuove configurazioni: **bin/drupal ci**

AGID-232 slim header (347)

---

web/themes/custom/agid/templates/block/block--header-top--slimheadermenu.html.twig
web/themes/custom/agid/templates/layout/page.html.twig

AGID-232 slim header (347) - Fix offcanvas

---

web/themes/custom/agid/css/agid.css
web/themes/custom/agid/scss/module/_slim-menu.scss

AGID-232 slim header (347) - Fix slim on hover.

---

web/themes/custom/agid/css/agid.css
web/themes/custom/agid/scss/module/_slim-menu.scss

AGID-232 slim header (347) - Fix colore slim menu.

---

config/agid/sync/block_titlelink.settings.yml
web/themes/custom/agid/agid.theme
web/themes/custom/agid/templates/block/block--homepageplatforms.html.twig
web/themes/custom/agid/templates/block/block--views-block--home-page-notizie-tecniche-block-1.html.twig

* Importare configurazioni: **bin/drupal ci**
* Pulire le cache: **bin/drupal cr**

AGID-241 modifica link tema (357)

---

config/agid/sync/core.entity_view_display.file.document.inside_content_page.yml
config/agid/sync/core.entity_view_display.file.document.thumbnail.yml
config/agid/sync/core.entity_view_display.file.image.thumbnail.yml
config/agid/sync/core.entity_view_display.file.media_kit.thumbnail.yml
web/themes/custom/agid/css/agid.css
web/themes/custom/agid/scss/base/_base.scss
web/themes/custom/agid/templates/fields/field--node--field-repository-files--news.html.twig
web/themes/custom/agid/templates/fields/field--node--field-repository-files--page.html.twig

Mostra la data personalizzata per le notizie e per le pagine.
* Importare configurazioni: **bin/drupal ci**

AGID-239 modifica data doc (354)

---

composer.json
composer.lock
config/agid/sync/core.extension.yml
config/agid/sync/eu_cookie_compliance.settings.yml
config/agid/sync/user.role.anonymous.yml
config/agid/sync/user.role.authenticated.yml
config/agid/sync/user.role.author.yml
config/agid/sync/user.role.publisher.yml
web/themes/custom/agid/agid.libraries.yml
web/themes/custom/agid/js/agid_analytics.js
web/themes/custom/agid/templates/layout/html.html.twig

Aggiunge script e modulo eu_cookie_compliance
* Importare configurazioni: **bin/drupal ci**

AGID-243 cookie bar e analytics (359)

---

web/themes/custom/agid/css/agid.css
web/themes/custom/agid/scss/layout/_header.scss

AGID-269 verifica logo IE11 (373) - Fixa logo svg su IE11

---

web/modules/custom/agid_repo_widget/src/Plugin/Field/FieldWidget/TableEntityReferenceBrowserWidget.php

Aggiornato plugin FieldWidget per utilizzi della proprietà,funzionalità 'tabledrag'
* Eseguire pulizia della cache: **bin/drupal cr all**

AGID-362 inserire drag-and-drop per documentazione (GyOedYPt) 

---

web/themes/custom/agid/css/agid.css
web/themes/custom/agid/scss/theme/_news.scss

**Descrizione**
Aggiornato codice colore per gli abstract delle notizie.
**Note di Deploy**
- Eseguire pulizia della cache: **./bin/drupal cr all**

AGID-450 Gli abstract delle notizie devono prevedere il codice #0059b3 (DJu03fgN)

---

web/themes/custom/agid/js/agid.js

AGID-451 da pagina linee guida non posso cliccare su menu progetti (W0tHgOrZ)

---

config/agid/sync/entity_browser.browser.repository_files_browser.yml

aggiornata configurazione di  per il caricamento dei files
* Importare configurazioni: **bin/drupal ci**

AGID-457 attivare formato csv per caricamento doc in CT pagina (HdlC9uKX)

---

web/modules/custom/content_changes_notify/content_changes_notify.module

AGID-459 Implementazione script per cambio status pagine (e7PIgWNy)

---

docroot/web/themes/custom/agid/templates/block/block--header-top--slimheadermenu.html.twig
docroot/web/themes/custom/agid/templates/block/block--system-branding-block.html.twig
docroot/web/themes/custom/agid/templates/layout/page--webform.html.twig
docroot/web/themes/custom/agid/templates/layout/page.html.twig
docroot/web/themes/custom/agid/templates/navigation/menu--slim-header-menu.html.twig
docroot/web/themes/custom/agid/templates/share_everywhere/share-everywhere.html.twig

This PR aims to increase Siteimprove accessibility score

AGID-547 Accessibility issues

---

docroot/config/agid/sync/views.view.search_site.yml
docroot/web/modules/custom/agid_search/src/Form/ViewsExposedFilterForm.php
docroot/web/themes/custom/agid/css/agid.css
docroot/web/themes/custom/agid/js/agid.js
docroot/web/themes/custom/agid/scss/theme/_serp.scss

This PR aims to solve issues listed in https://docs.google.com/document/d/16DlyHYZIS-7ampfOHR_ylVMa9hRhhd55mwXUuAC8tPM/edit#
The solution to issue#9 needs the following commands to be run
```
$ make shell
$ bin/drush -r /var/www/html/web cim -y
$ bin/drush -r /var/www/html/web cr
```

AGID-548 - AGID-548 Solr bugfixing (V7XwS9p2) - Soluzione punti 1-5, 7-9, 11, 14, 16-18 del documento delle segnalazioni
